# Generated by Django 2.1.5 on 2019-02-06 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='linktopapers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('authorshortcut', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('webpage', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Science',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('lab_involvment', models.CharField(max_length=200)),
                ('popularity', models.CharField(max_length=100)),
                ('picture', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='subfield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maths_heavy', models.CharField(max_length=10)),
                ('time_to_be_competent', models.CharField(max_length=250)),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ScienceBlog.Science')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UniProt', models.CharField(max_length=20, unique=True)),
                ('InitDate', models.DateTimeField(auto_now_add=True)),
                ('Title', models.CharField(max_length=10)),
            ],
        ),
    ]
